services:

  tdw:
    extends:
      file: docker/compose.yaml
      service: tdw
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://tdw:inOrbit@localhost:5432/tdw-db
      - NODE_ENV=development
      - MAX_ANNOTATIONS_PER_VIDEO=3

  database:
    image: postgres:15
    container_name: tdw-db
    environment:
      - POSTGRES_USER=tdw
      - POSTGRES_PASSWORD=inOrbit
      - POSTGRES_DB=tdw-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # postgrest:
  #   image: postgrest/postgrest
  #   container_name: tdw-db-api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     PGRST_DB_URI: postgres://tdw:inOrbit@database:5432/tdw-db
  #     PGRST_DB_SCHEMA: public
  #     PGRST_DB_ANON_ROLE: tdw
  #   depends_on:
  #     - database

volumes:
  postgres_data: